### ISSUE TITLE
Allow spaces in tags and more than one tag per prompt

### ISSUE THREAD

**Issue by Werpers** [fwerpers/timeprof#2]
Tags should be able to contain spaces to make them more flexible.
Multiple tags for one prompt should also be allowed and separated by e.g. ",".

**Comment by fwerpers** [comment]
What is the definition of a tag really? Should the bot ever be concerned about what a tag is? Or should the bot just be a recorder of arbitrary strings where it's up to the user to interpret the strings?

**Comment by Werpers** [comment]
I guess the bot doesn't necessarily have to know how to parse tags, but the analysis tool must have some kind of definition. Perhaps the only definition the bot needs to care about is that there is no conflict between what a tag is and the command character if #4 is implemented.

My suggestion is that any string that doesn't start with the command character is considered a tag for now. The definition can become more strict when we start to develop the analysis tool.
